### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by PsychoLlama** [retreon/retreon#219]
Retreon needs a logo for both the project and the organization.

**Comment by PsychoLlama** [comment]
I've created a stand-in until I get something more permanent. This should do for now.

<img src="https://user-images.githubusercontent.com/10053423/99162874-abe95b80-26b7-11eb-8d9a-689bf83aa414.png" alt="Retreon Logo" width="150" />

**Comment by PsychoLlama** [comment]
Here's a better logo:
<img src="https://user-images.githubusercontent.com/10053423/99501303-6e433780-2930-11eb-9bd5-a498e69d6189.png" width="200" alt="Retreon Logo" />

And the transparent version...
<img src="https://user-images.githubusercontent.com/10053423/99501366-7ef3ad80-2930-11eb-935a-b5b6788575a4.png" width="200" alt="Transparent Retreon Logo" />

Admittedly not great on a white background, but considering that I'm a design n00b, it could've been worse. I'm calling this a success!

**Comment by metasean** [comment]
fwiw: I much prefer the glowy red, green, blue logo!

**Comment by PsychoLlama** [comment]
Thanks! I'm happy with how it turned out. I also tried red + green + orange, but that's just the Chrome logo 🙃
